export const CREATE_AIRPORT_REQUEST = "CREATE_AIRPORT_REQUEST";
export const CREATE_AIRPORT_SUCCESS = "CREATE_AIRPORT_SUCCESS";
export const CREATE_AIRPORT_FAILURE = "CREATE_AIRPORT_FAILURE";

export const GET_ALL_AIRPORT_REQUEST = "GET_ALL_AIRPORT_REQUEST";
export const GET_ALL_AIRPORT_SUCCESS = "GET_ALL_AIRPORT_SUCCESS";
export const GET_ALL_AIRPORT_FAILURE = "GET_ALL_AIRPORT_FAILURE";

export const UPDATE_AIRPORT_REQUEST = "UPDATE_AIRPORT_REQUEST";
export const UPDATE_AIRPORT_SUCCESS = "UPDATE_AIRPORT_SUCCESS";
export const UPDATE_AIRPORT_FAILURE = "UPDATE_AIRPORT_FAILURE";

export const DELETE_AIRPORT_REQUEST = "DELETE_AIRPORT_REQUEST";
export const DELETE_AIRPORT_SUCCESS = "DELETE_AIRPORT_SUCCESS";
export const DELETE_AIRPORT_FAILURE = "DELETE_AIRPORT_FAILURE";
