export const CREATE_AIRPLANE_REQUEST = "CREATE_AIRPLANE_REQUEST";
export const CREATE_AIRPLANE_SUCCESS = "CREATE_AIRPLANE_SUCCESS";
export const CREATE_AIRPLANE_FAILURE = "CREATE_AIRPLANE_FAILURE";

export const GET_ALL_AIRPLANE_REQUEST = "GET_ALL_AIRPLANE_REQUEST";
export const GET_ALL_AIRPLANE_SUCCESS = "GET_ALL_AIRPLANE_SUCCESS";
export const GET_ALL_AIRPLANE_FAILURE = "GET_ALL_AIRPLANE_FAILURE";

export const UPDATE_AIRPLANE_REQUEST = "UPDATE_AIRPLANE_REQUEST";
export const UPDATE_AIRPLANE_SUCCESS = "UPDATE_AIRPLANE_SUCCESS";
export const UPDATE_AIRPLANE_FAILURE = "UPDATE_AIRPLANE_FAILURE";

export const DELETE_AIRPLANE_REQUEST = "DELETE_AIRPLANE_REQUEST";
export const DELETE_AIRPLANE_SUCCESS = "DELETE_AIRPLANE_SUCCESS";
export const DELETE_AIRPLANE_FAILURE = "DELETE_AIRPLANE_FAILURE";
