export const GET_ALL_HIGHLIGHTED_FLIGHT_REQUEST =
  "GET_ALL_HIGHLIGHTED_FLIGHT_REQUEST";
export const GET_ALL_HIGHLIGHTED_FLIGHT_SUCCESS =
  "GET_ALL_HIGHLIGHTED_FLIGHT_SUCCESS";
export const GET_ALL_HIGHLIGHTED_FLIGHT_FAILURE =
  "GET_ALL_HIGHLIGHTED_FLIGHT_FAILURE";
