export const GET_INBOUND_FLIGHT_REQUEST = "GET_INBOUND_FLIGHT_REQUEST";
export const GET_INBOUND_FLIGHT_SUCCESS = "GET_INBOUND_FLIGHT_SUCCESS";
export const GET_INBOUND_FLIGHT_FAILURE = "GET_INBOUND_FLIGHT_FAILURE";

export const GET_OUTBOUND_FLIGHT_REQUEST = "GET_OUTBOUND_FLIGHT_REQUEST";
export const GET_OUTBOUND_FLIGHT_SUCCESS = "GET_OUTBOUND_FLIGHT_SUCCESS";
export const GET_OUTBOUND_FLIGHT_FAILURE = "GET_OUTBOUND_FLIGHT_FAILURE";

export const ADD_GET_FLIGHT_REQUEST = "ADD_GET_FLIGHT_REQUEST";
export const ADD_GET_INBOUND_FLIGHT_REQUEST = "ADD_GET_INBOUND_FLIGHT_REQUEST";

export const ADD_SELECTED_OUTBOUND_FLIGHT = "ADD_SELECTED_OUTBOUND_FLIGHT";
export const ADD_SELECTED_INBOUND_FLIGHT = "ADD_SELECTED_INBOUND_FLIGHT";
