export const CREATE_FLIGHT_REQUEST = "CREATE_FLIGHT_REQUEST";
export const CREATE_FLIGHT_SUCCESS = "CREATE_FLIGHT_SUCCESS";
export const CREATE_FLIGHT_FAILURE = "CREATE_FLIGHT_FAILURE";

export const GET_ALL_FLIGHT_REQUEST = "GET_ALL_FLIGHT_REQUEST";
export const GET_ALL_FLIGHT_SUCCESS = "GET_ALL_FLIGHT_SUCCESS";
export const GET_ALL_FLIGHT_FAILURE = "GET_ALL_FLIGHT_FAILURE";

export const UPDATE_FLIGHT_REQUEST = "UPDATE_FLIGHT_REQUEST";
export const UPDATE_FLIGHT_SUCCESS = "UPDATE_FLIGHT_SUCCESS";
export const UPDATE_FLIGHT_FAILURE = "UPDATE_FLIGHT_FAILURE";

export const DELETE_FLIGHT_REQUEST = "DELETE_FLIGHT_REQUEST";
export const DELETE_FLIGHT_SUCCESS = "DELETE_FLIGHT_SUCCESS";
export const DELETE_FLIGHT_FAILURE = "DELETE_FLIGHT_FAILURE";
