export const GET_FLIGHT_INSTANCE_BY_USER_REQUEST =
  "GET_FLIGHT_INSTANCE_BY_USER_REQUEST";
export const GET_FLIGHT_INSTANCE_BY_USER_SUCCESS =
  "GET_FLIGHT_INSTANCE_BY_USER_SUCCESS";
export const GET_FLIGHT_INSTANCE_BY_USER_FAILURE =
  "GET_FLIGHT_INSTANCE_BY_USER_FAILURE";
