export const CREATE_SEAT_REQUEST = "CREATE_SEAT_REQUEST";
export const CREATE_SEAT_SUCCESS = "CREATE_SEAT_SUCCESS";
export const CREATE_SEAT_FAILURE = "CREATE_SEAT_FAILURE";

export const ADD_CUSTOMER = "ADD_CUSTOMER";

export const GET_SEAT_BY_USER_AND_FLIGHT_INSTANCE_REQUEST =
  "GET_SEAT_BY_USER_AND_FLIGHT_INSTANCE_REQUEST";
export const GET_SEAT_BY_USER_AND_FLIGHT_INSTANCE_SUCCESS =
  "GET_SEAT_BY_USER_AND_FLIGHT_INSTANCE_SUCCESS";
export const GET_SEAT_BY_USER_AND_FLIGHT_INSTANCE_FAILURE =
  "GET_SEAT_BY_USER_AND_FLIGHT_INSTANCE_FAILURE";

export const GET_SEAT_MAP_REQUEST = "GET_SEAT_MAP_REQUEST";
export const GET_SEAT_MAP_SUCCESS = "GET_SEAT_MAP_SUCCESS";
export const GET_SEAT_MAP_FAILURE = "GET_SEAT_MAP_FAILURE";
