export const CREATE_SEAT_REQUEST = "CREATE_SEAT_REQUEST";
export const CREATE_SEAT_SUCCESS = "CREATE_SEAT_SUCCESS";
export const CREATE_SEAT_FAILURE = "CREATE_SEAT_FAILURE";

export const ADD_CUSTOMER = "ADD_CUSTOMER";
