export const GET_ALL_HERO_BANNER_REQUEST = "GET_ALL_HERO_BANNER_REQUEST";
export const GET_ALL_HERO_BANNER_SUCCESS = "GET_ALL_HERO_BANNER_SUCCESS";
export const GET_ALL_HERO_BANNER_FAILURE = "GET_ALL_HERO_BANNER_FAILURE";
