export const GET_FLIGHT_INSTANCE_BY_ADMIN_REQUEST =
  "GET_FLIGHT_INSTANCE_BY_ADMIN_REQUEST";
export const GET_FLIGHT_INSTANCE_BY_ADMIN_SUCCESS =
  "GET_FLIGHT_INSTANCE_BY_ADMIN_SUCCESS";
export const GET_FLIGHT_INSTANCE_BY_ADMIN_FAILURE =
  "GET_FLIGHT_INSTANCE_BY_ADMIN_FAILURE";

export const CREATE_FLIGHT_INSTANCE_BY_ADMIN_REQUEST =
  "CREATE_FLIGHT_INSTANCE_BY_ADMIN_REQUEST";
export const CREATE_FLIGHT_INSTANCE_BY_ADMIN_SUCCESS =
  "CREATE_FLIGHT_INSTANCE_BY_ADMIN_SUCCESS";
export const CREATE_FLIGHT_INSTANCE_BY_ADMIN_FAILURE =
  "CREATE_FLIGHT_INSTANCE_BY_ADMIN_FAILURE";

export const UPDATE_FLIGHT_INSTANCE_BY_ADMIN_REQUEST =
  "UPDATE_FLIGHT_INSTANCE_BY_ADMIN_REQUEST";
export const UPDATE_FLIGHT_INSTANCE_BY_ADMIN_SUCCESS =
  "UPDATE_FLIGHT_INSTANCE_BY_ADMIN_SUCCESS";
export const UPDATE_FLIGHT_INSTANCE_BY_ADMIN_FAILURE =
  "UPDATE_FLIGHT_INSTANCE_BY_ADMIN_FAILURE";

export const UPDATE_LEG_INSTANCE_BY_ADMIN_REQUEST =
  "UPDATE_LEG_INSTANCE_BY_ADMIN_REQUEST";
export const UPDATE_LEG_INSTANCE_BY_ADMIN_SUCCESS =
  "UPDATE_LEG_INSTANCE_BY_ADMIN_SUCCESS";
export const UPDATE_LEG_INSTANCE_BY_ADMIN_FAILURE =
  "UPDATE_LEG_INSTANCE_BY_ADMIN_FAILURE";
